/**
 * Created by ningzedai on 5/31/16.
 */
export const CustomerActions = {
	SELECT_CUSTOMER: 'SELECT_CUSTOMER',
	LEADS_ON: 'LEADS_ON',
	SET_CUSTOMERS: 'SET_CUSTOMERS',
    SEARCH_CUSTOMER: 'SEARCH_CUSTOMER',
    CREATE_CUSTOMER: 'CREATE_CUSTOMER',
    SHOW_LIST: 'SHOW_LIST',
    SHOW_GRID: 'SHOW_GRID',
    ADD_CUSTOMER_QUESTION: 'ADD_CUSTOMER_QUESTION',
    EDIT_CUSTOMER_INFO: 'EDIT_CUSTOMER_INFO',
    EDIT_QUESTION: 'EDIT_QUESTION'
}

export const OrderActions = {
    SELECT_ORDER: 'SELECT_ORDER',
    ADD_ORDER: 'ADD_ORDER',
    REMOVE_ORDER: 'REMOVE_ORDER'
}

export const InventoryActions = {
    CHANGE_SERVING_SIZE: 'CHANGE_SERVING_SIZE',
    CHANGE_CALORIES_PER_SERVING: 'CHANGE_CALORIES_PER_SERVING',
    CHANGE_SERVINGS_PER_CONTAINER: 'CHANGE_SERVINGS_PER_CONTAINER'
}

export const MealActions = {
    CREATE_MEAL: 'CREATE_MEAL',
    SELECT_MEAL: 'SELECT_MEAL',
    SELECT_CATEGORY: 'SELECT_CATEGORY',
    ADD_HERBALIFE_PRODUCT: 'ADD_HERBALIFE_PRODUCT',
    ADD_OTHER_INGREDIENTS: 'ADD_OTHER_INGREDIENTS',
    CHANGE_SERVING: 'CHANGE_SERVING'
}